#CoAP
import logging

COAP_GATEWAY_HOST = 'localhost'
COAP_GATEWAY_PORT = 5688
COAP_RETENT_MAX_TIME = 120

#WebSocket
WS_GATEWAY_HOST  = 'localhost'
WS_GATEWAY_PORT = 8004

#MQTT
MQTT_BROKER_HOST = 'localhost'
MQTT_BROKER_PORT = 1886
MQTT_RETENT_MAX_TIME = 120

#LOG_SETTING
LOG_LEVEL = logging.DEBUG

